#!/usr/bin/env python3
"""Generate a C program that emits fasmg `assert` lines for every struct,
field, and integer constant declared in bindings/fasm2/box3d.inc.

The C program is compiled against include/box3d, so the printed offsets and
sizes are the C compiler's ground truth. Assembling test_layout.asm, which
includes box3d.inc followed by the generated layout_check.inc, fails if the
fasm2 bindings disagree with the C ABI in any offset, size, or constant.

Usage: python gen_layout.py <box3d.inc> <out.c>
"""

import re
import sys


def main() -> None:
    inc_path, out_path = sys.argv[1], sys.argv[2]

    structs = []  # (struct_name, [field, ...])
    consts = []   # constant names
    cur = None
    union_depth = 0

    field_re = re.compile(r"^\s+([A-Za-z_][A-Za-z0-9_]*)\s+\S")
    const_re = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(\S+)")

    for line in open(inc_path, encoding="utf-8"):
        code = line.split(";", 1)[0].rstrip()
        if not code:
            continue
        m = re.match(r"^struct\s+([A-Za-z0-9_]+)", code)
        if m:
            cur = (m.group(1), [])
            structs.append(cur)
            union_depth = 0
            continue
        if cur is not None:
            stripped = code.strip()
            if stripped == "union":
                union_depth += 1
                continue
            if stripped == "ends":
                if union_depth:
                    union_depth -= 1
                else:
                    cur = None
                continue
            m = re.match(r"^\s+label\s+([A-Za-z_][A-Za-z0-9_]*)\s*:", code)
            if m:  # fields whose C name collides with a fasm2 directive
                cur[1].append(m.group(1))
                continue
            m = field_re.match(code)
            if m and m.group(1) not in ("rb", "rw", "rd", "rq", "label"):
                cur[1].append(m.group(1))
            continue
        m = const_re.match(code)
        if m and "." not in m.group(2):  # skip float constants
            consts.append(m.group(1))

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Generated by gen_layout.py -- do not edit.\n")
        f.write("#include <stdio.h>\n#include <stddef.h>\n")
        f.write('#include "box3d/box3d.h"\n\n')
        f.write("int main(void)\n{\n")
        f.write('\tprintf("; generated layout ground truth from the C compiler\\n");\n')
        for name in consts:
            # Mask to 64 bits on both sides so negative constants compare
            # equal regardless of fasmg's arbitrary-precision arithmetic.
            f.write(f'\tprintf("assert ({name}) and 0xFFFFFFFFFFFFFFFF = %llu\\n", '
                    f"(unsigned long long)({name}));\n")
        for sname, fields in structs:
            f.write(f'\tprintf("assert sizeof.{sname} = %zu\\n", sizeof({sname}));\n')
            for field in fields:
                f.write(f'\tprintf("assert {sname}.{field} = %zu\\n", '
                        f"offsetof({sname}, {field}));\n")
        f.write("\treturn 0;\n}\n")

    total = sum(len(f) for _, f in structs)
    print(f"{len(structs)} structs, {total} fields, {len(consts)} constants")


if __name__ == "__main__":
    main()
